import React from 'react';
import type { Metadata } from 'next';
import './globals.css';
import ReactLenis from 'lenis/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body className="bg-background">
          <main className="min-h-screen">{children}</main>
        </body>
      </ReactLenis>
    </html>
  );
}
