import React from 'react';
import type { Metadata } from 'next';
import './globals.css';
import ReactLenis from 'lenis/react';
import OrderPopup from '@/components/organisms/OrderPopup';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background">
        <ReactLenis root>
          <main className="min-h-screen">{children}</main>
        </ReactLenis>

        <OrderPopup />
      </body>
    </html>
  );
}
